# Generated by Django 3.1.6 on 2021-03-28 23:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calendars', '0002_auto_20210225_0035'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CalendarEvent',
        ),
    ]
