"""
Django settings for infomationhub project.

Generated by 'django-admin startproject' using Django 3.0.3.

For more information on this file, see
https://docs.djangoproject.com/en/3.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.0/ref/settings/
"""

import os

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.0/howto/deployment/checklist/

SECRET_KEY = os.environ['SECRET_KEY']

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = [
    "young-adult-liver-service.herokuapp.com",
    "localhost", 
    "127.0.0.1"
]

# Application definition

INSTALLED_APPS = [
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',    
    
    # Project apps
    'accounts',
    'hub',
    'calendars',
    'core',
    'events',
    'forum',
    'pages',
    'news',
    'faq',
    'help_support',

    
    # Libraries
    'phonenumber_field',
    'ckeditor',
    'ckeditor_uploader',
    'crispy_forms',

    'django.contrib.admin',
    'django.contrib.auth',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'informationhub.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS' : [os.path.join(BASE_DIR, 'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
            
        },
    },
]

WSGI_APPLICATION = 'informationhub.wsgi.application'

# Database
# https://docs.djangoproject.com/en/3.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
    }
}

import dj_database_url

db_from_env = dj_database_url.config()
DATABASES['default'].update(db_from_env)

# Password validation
# https://docs.djangoproject.com/en/3.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Internationalization
# https://docs.djangoproject.com/en/3.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True

CSRF_COOKIE_SECURE = True

SESSION_COOKIE_SECURE = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.0/howto/static-files/

STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')

STATIC_URL = '/static/'

STATICFILES_DIRS = [
    os.path.join(BASE_DIR, 'static'),
]

MEDIA_ROOT = os.path.join(BASE_DIR, 'media')
MEDIA_URL = '/media/'

CKEDITOR_JQUERY_URL = 'https://ajax.googleapis.com/ajax/libs/jquery/2.2.4/jquery.min.js'

CKEDITOR_UPLOAD_PATH = "ckeditor/"
CKEDITOR_IMAGE_BACKEND = "pillow"
CKEDITOR_ALLOW_NONIMAGE_FILES = False

CKEDITOR_CONFIGS = {
    'default': {
        'toolbar_Basic': [
            ['Source', '-', 'Bold', 'Italic']
        ],
	'custom_toolbar': [
		{ 'name': 'document', 'groups': [ 'mode', 'document', 'doctools' ] },
		{ 'name': 'clipboard', 'groups': [ 'undo', 'clipboard' ] },
		{ 'name': 'editing', 'groups': [ 'find', 'selection', 'spellchecker', 'editing' ] },
		{ 'name': 'forms', 'groups': [ 'forms' ] },
		'/',
		{ 'name': 'insert', 'groups': [ 'insert' ] },
		{ 'name': 'paragraph', 'groups': [ 'list', 'indent', 'blocks', 'align', 'bidi', 'paragraph' ] },
		{ 'name': 'links', 'groups': [ 'links' ] },
		{ 'name': 'colors', 'groups': [ 'colors' ] },
		'/',
		{ 'name': 'styles', 'groups': [ 'styles' ] },
		{ 'name': 'basicstyles', 'groups': [ 'basicstyles', 'cleanup' ] },
		{ 'name': 'tools', 'groups': [ 'tools' ] },
		{ 'name': 'others', 'groups': [ 'others' ] },
		{ 'name': 'about', 'groups': [ 'about' ] }
	],
    'toolbar': 'custom_toolbar',
    'removeButtons': 'ImageButton,Save,Print,Smiley,CreateDiv,Language,TextField,Textarea,Maximize,ShowBlocks,NewPage,Flash,Templates',
    'extraPlugins': ','.join([
            'uploadimage'])
    }
}
# Authentication 
AUTH_USER_MODEL = 'accounts.User'

# Login
LOGIN_REDIRECT_URL='/'
LOGOUT_REDIRECT_URL = '/'
LOGIN_URL = '/login/'

# SMTP Configuration
EMAIL_FILE_PATH = os.path.join(BASE_DIR, 'sent_emails')
EMAIL_BACKEND = "django.core.mail.backends.smtp.EmailBackend"
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_PORT = 587
EMAIL_USE_TLS = True
EMAIL_HOST_USER = os.environ['EMAIL_ID'] 
EMAIL_HOST_PASSWORD = os.environ['EMAIL_PW']
